### PR TITLE
Added firebase for realtime moves

### PR DESCRIPTION
**Pull request by jackpip**
It seems to be working on my end. If someone can confirm that would be great. Basically this should make it so that when you make a move it should automatically update for the other player. You can test this by opening up two tabs, each for the game and then on one of them move the pieces around a bit, and the pieces should automatically move on the other one.

This was pretty tricky for me, so some of the could could probably have been written better.

### CODE REVIEW

**Comment by bjvoth** [comment]
Hey @jackpip, I just pulled this down. On my machine it takes a refresh to see the move get updated.

**Comment by jackpip** [comment]
@bjvoth Interesting,  I will take a look at it. Did you make sure to run a bundle install, and make sure that both pages are refreshed before trying?

**Comment by jackpip** [comment]
Also, if it's still not working, check the javascript consoles of both pages in the developer tools and see if anything pops up and let me know.

**Comment by bjvoth** [comment]
@jackpip I tried starting again from scratch. Fetched the branch, pulled down latest changes, bundle install, then start my server. Open two fresh tabs, join the same game (which for some reason says "Not allowed". The fix for me is just to enter the same url into my browser. Not sure what that is about...) then make moves in either tab. The results this time were the same. The moves update on my current tab, but not on the other tab. I checked both tabs' consoles for any JS messages - all I'm seeing is an error from facebook.js, which I think is unrelated. I checked my server logs for any info, but there is nothing out of the ordinary there either. @EmmanuelJucaban @MarcMcArthur @janetmohler can anyone else reproduce this, or is it something specific to my local machine?

**Comment by OxManny-Dev** [comment]
I'll try and reproduce this today,

**Comment by jackpip** [comment]
I know this can't be merged at the moment, but I changed some things around, and maybe it will have fixed the problems @bjvoth was having. It's still working for me locally.

**Comment by bjvoth** [comment]
Hey @jackpip sorry to keep making you work on this. After pulling down the most recent changes, I'm noticing a slight improvement. In the tab that I first enter the game with (tab1), I'm able to make moves (though there is a slight delay in the jQuery updating) and they show up in the other tab (tab2) right away. But when I try to make moves in tab2 (the one that tells me Not Allowed when I first try to join the game, which I bypass by entering the game id url), the piece hovers, and doesn't drop on to the square I selected until I refresh the page. Also, when I do refresh tab2 to see the moves, and I click back to tab1, the moves are not updated, again requiring a refresh.

How do you get two tabs of the same game? Do you get the same error message as me? And do both of your tabs work equally well?

**Comment by jackpip** [comment]
Cool,  that's definitely a step in the right direction. For opening the same game I just copy the url like you said. I believe you get the error message because someone probably put in a check to make sure the same user isn't joining as both the white and black player for the same game. Which is good I think.

**Comment by bjvoth** [comment]
@jackpip Yeah I thought that was it too, but then I tried to join as two separate users and got the same message. Weird, but relatively minor.

**Comment by jackpip** [comment]
Okay @bjvoth and anyone else who can test this, I made some changes and I hope this works for you!

**Comment by bjvoth** [comment]
@jackpip Just tested. This is the best one yet. I'm still noticing some delay in the jQuery piece dropping. 

On master branch if I click once and then drag to a valid square, the piece drops onto the square when I let go of the mouse and the square gets highlighted.

On the adding-web-sockets-firebase branch if I click once on the piece and drag it to a valid square, I can release the mouse and the piece stays on the square I dropped it on, but the square isn't highlighted. In this scenario, the other tab does not update with the move. Both tabs require a refresh to reflect the current state of the board.

Most times if I just click on the square I want the piece to go to again, the pieces settles in to the middle and the square gets highlighted, at which point the move is updated in the other tab. I'm not sure what would be causing the jQuery delay, but unless you (or anyone else, though it seems like most folks have checked out) have some ideas left for what it might be, I'd say we could just merge this.

**Pull request merged**
